### ISSUE TITLE
AddBorder APE

### ISSUE THREAD

**Issue by grandchild** [grandchild/vis_avs#16]

**Comment by grandchild** [comment]
@goebish FYI.

**Comment by goebish** [comment]
You could have asked me for original source code ;)

**Comment by grandchild** [comment]
I didn't think of it, and it was so easy to do :)

**Comment by grandchild** [comment]
@goebish  do you have a website i should link to in the credits? otherwise i will link to your github profile.

**Comment by goebish** [comment]
Please link to github, otherwise I have an (old) webpage with my APEs:
http://goebish.free.fr/vfx/

Feel free to ask if you need original source code ;)
